default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://enwqcxwb:eYBh647HEpOXER3ZyVTqcXnL1Lt4goZx@dumbo.db.elephantsql.com/enwqcxwb

production:
  <<: *default
  url: postgres://enwqcxwb:eYBh647HEpOXER3ZyVTqcXnL1Lt4goZx@dumbo.db.elephantsql.com/enwqcxwb
